### ISSUE TITLE
Readme not up-to-date

### ISSUE THREAD

**Issue by seza443** [craigvincent/nunit-console-dockerfile#2]
Hi,

In your Readme, you should update the clone name. Instead of

    craigvincent/docker-nunit-console

It should be

    craigvincent/nunit-console

Because docker searches for the repo in docker hub and the name is slighly different there.

Best regards,
Tanguy

**Comment by craigvincent** [comment]
Cheers for pointing that out Tanguy 😄 Updated readme to correct
